FROM node:20 AS builder

WORKDIR /sync/app

COPY package*.json ./

RUN npm install

COPY . .

ARG MODE=production

RUN npm run build -- --mode $MODE


FROM nginx:alpine

COPY --from=builder /sync/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]